---
title: "3.1 - Logistic Regression"
output: html_notebook
author: Glenn Bucagu
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/Projects/Machine Learning A-Z (Codes and Datasets)/Part 3 - Classification/Section 14 - Logistic Regression/R")
```


```{r importing dataset}
dataset <- read.csv("Social_Network_Ads.csv")[3:5] 
# For simplicity, we only use age and estimated salary as features
dataset
```

```{r splitting the dataset into training and testing set}
library(caTools)
split = sample.split(dataset$Purchased, SplitRatio = 0.75)
training_set = subset(dataset, split == TRUE)
testing_set = subset(dataset, split == FALSE)

training_set
testing_set

```

```{r feature scaling}

training_set[, 1:2] <- scale(training_set[, 1:2])
testing_set[, 1:2] <- scale(testing_set[, 1:2])

training_set
testing_set

```


```{r fitting logistic regression model}
classifier <- glm(formula = Purchased ~ .,
                 family = binomial, 
                 data = training_set)
summary(classifier)
```

```{r predicting testing set results}
prob_pred <- predict(classifier, 
                     type = "response", 
                     newdata = testing_set[-3]) 

y_pred = ifelse(prob_pred > 0.5, 1, 0)
y_pred 

```

```{r generating the confusion matrix}

confusion_matrix <- table(testing_set[, 3], y_pred)
confusion_matrix

# 57/64 correct predictions of class 0
# 22/36 correct predictions of class 1

```

```{r visualizing training set results}
# install.packages("~/Downloads/ElemStatLearn_2015.6.26.tar", type = "source", repos = NULL)
library(ElemStatLearn)
set = training_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c("Age", "EstimatedSalary")
prob_set = predict(classifier, type = "response", newdata = grid_set)
y_grid = ifelse(prob_set > 0.5, 1, 0)
plot(set[, -3], 
     main = "Logistic Regression (training set)", 
     xlab = "Age", ylab = "Estimated Salary ($)", 
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = ".", col = ifelse(y_grid == 1, "springgreen3", "tomato"))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, "green4", "red3"))


```



```{r visualizing testing set results}
# install.packages("~/Downloads/ElemStatLearn_2015.6.26.tar", type = "source", repos = NULL)
library(ElemStatLearn)
set = testing_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c("Age", "EstimatedSalary")
prob_set = predict(classifier, type = "response", newdata = grid_set)
y_grid = ifelse(prob_set > 0.5, 1, 0)
plot(set[, -3], 
     main = "Logistic Regression (training set)", 
     xlab = "Age", ylab = "Estimated Salary ($)", 
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = ".", col = ifelse(y_grid == 1, "springgreen3", "tomato"))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, "green4", "red3"))


```

