---
title: "3.5 - Naive Bayes"
output: html_notebook
author: Glenn Bucagu
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/Projects/Machine Learning A-Z (Codes and Datasets)/Part 3 - Classification/Section 18 - Naive Bayes/R")
```


```{r importing dataset}
dataset <- read.csv("Social_Network_Ads.csv")[3:5] 
# For simplicity, we only use age and estimated salary as features
dataset
```

```{r splitting the dataset into training and testing set}

library(caTools)
split = sample.split(dataset$Purchased, SplitRatio = 0.75)
training_set = subset(dataset, split == TRUE)
testing_set = subset(dataset, split == FALSE)

training_set
testing_set

```

```{r feature scaling}
training_set[-3] = scale(training_set[-3])
testing_set[-3] = scale(testing_set[-3])

training_set
testing_set

```

```{r building the Naive Bayes model}
library(e1071)

#first encode the target feature as a factor
# this will allow Naive Bayes function to work well
training_set$Purchased = factor(x = training_set$Purchased,
                                levels = c(0, 1))

classifier = naiveBayes(x = training_set[-3],
                        y = training_set$Purchased)
summary(classifier)

```

```{r predicting values from testing set}
y_pred <- predict(classifier, testing_set)
y_pred

```

```{r classification report}
confusion_matrix <- table(testing_set[, 3], y_pred)
confusion_matrix

```


```{r visualizing training set results}
# install.packages("~/Downloads/ElemStatLearn_2015.6.26.tar", type = "source", repos = NULL)
library(ElemStatLearn)
set = training_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c("Age", "EstimatedSalary")
y_grid = predict(classifier, newdata = grid_set)
plot(set[, -3], 
     main = "Naive Bayes (training set)", 
     xlab = "Age", ylab = "Estimated Salary ($)", 
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = ".", col = ifelse(y_grid == 1, "springgreen3", "tomato"))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, "green4", "red3"))


```


```{r visualizing testing set results}
# install.packages("~/Downloads/ElemStatLearn_2015.6.26.tar", type = "source", repos = NULL)
library(ElemStatLearn)
set = testing_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c("Age", "EstimatedSalary")
y_grid = predict(classifier, newdata = grid_set)
plot(set[, -3], 
     main = "Naive Bayes (training set)", 
     xlab = "Age", ylab = "Estimated Salary ($)", 
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = ".", col = ifelse(y_grid == 1, "springgreen3", "tomato"))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, "green4", "red3"))


```

