---
title: "4.1 - K-Means Clustering"
output: html_notebook
author: Glenn Bucagu
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/Projects/Machine Learning A-Z (Codes and Datasets)/Part 4 - Clustering/Section 24 - K-Means Clustering/R")
```


```{r importing dataset}
dataset <- read.csv("Mall_Customers.csv") 
dataset

# Using desired feature and output variable
X <- dataset[4:5]
X
```


```{r elbow method for optimal number of clusters}
set.seed(6)
wcss <- vector() # Within Cluster Sum of Squares vector

for (i in 1:10) {
  wcss[i] <- sum(kmeans(X, i)$withinss)
}
plot(1:10, wcss, type = "b", main = paste("Clusters of Clients"),
     xlab = "Number of clusters", ylab = "WCSS")

#Our plot shows us the optimal number of clusters is 5 clusters

```

```{r fitting the k-means model}
set.seed(29)
kmeans <- kmeans(x = X,
                 centers = 5, 
                 iter.max = 10, 
                 nstart = 10)
```

```{r visualizing the clusters}
#install.packages("cluster")
library(cluster)
clusplot(x = X,
         main = paste("Clusters of elements"),
         clus = kmeans$cluster,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels = 2,
         plotchar = FALSE,
         xlab = "Annual Income ($)",
         ylab = "Spending Score")

```

