---
title: "8 - Artificial Neural Networks"
output: html_notebook
author: Glenn Bucagu
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/Projects/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/R")
```

```{r importing the dataset}
dataset <- read.csv("Churn_Modelling.csv")[4:14]
dataset
```

```{r pre-processing}
# Encoding categorical variables as factors

dataset$Geography <- as.numeric(factor(dataset$Geography, 
                            levels = c("France", "Spain", "Germany"),
                            labels = c(1, 2, 3)))
dataset$Gender <- as.numeric(factor(dataset$Gender,
                         levels = c("Female", "Male")))

dataset
```


```{r splitting the dataset into training and testing set}
library(caTools)
set.seed(123)
split = sample.split(dataset$Exited, SplitRatio = 0.8)
training_set <- subset(dataset, split == TRUE)
test_set <- subset(dataset, split == FALSE)

```

```{r feature scaling}
training_set[-11] <- scale(training_set[-11])
test_set[-11] <- scale(test_set[-11])
training_set
test_set



```

```{r building the ANN}
# install.packages("h2o")
library(h2o)
# need to establish server connection to run 
# number of cores in system
h2o.init(nthreads = -1)
classifier <- h2o.deeplearning(y = "Exited",
                               training_frame = as.h2o(training_set),
                               activation = "Rectifier",
                               hidden = c(6, 6),
                               epochs = 100,
                               train_samples_per_iteration = -2)

        

```

```{r evaluating the model}
set.seed(123)
prob_pred <- h2o.predict(classifier, newdata = as.h2o(test_set[-11]))
y_pred <- ifelse(prob_pred > 0.5, 1, 0)
y_pred <- as.vector(y_pred)
confusion_matrix <- table(test_set[, 11], y_pred)
confusion_matrix

h2o.shutdown()

```

